// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalManager.Infrastructure.Persistence.PgSql.Contexts;

#nullable disable

namespace PersonalManager.Infrastructure.Migrations
{
    [DbContext(typeof(PgSqlContext))]
    [Migration("20251023073450_PersonalManager")]
    partial class PersonalManager
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonaManager.Domain.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountLabel")
                        .HasColumnType("text");

                    b.Property<string>("Bic")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<string>("Rib")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDependent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContratReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<float?>("SalaryMensual")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TypeContrat")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentDepartmentId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("ParentDepartmentId1");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Establishment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Graduation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GraduationYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdChild")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildId1");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Civility")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("DepartementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Bank", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonaManager.Domain.Entities.Employee", null)
                        .WithMany("Banks")
                        .HasForeignKey("EmployeeId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Child", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Employee", null)
                        .WithMany("Children")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonaManager.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PersonaManager.Domain.ValuesObject.Identity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("ChildId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .HasColumnType("text");

                            b1.Property<string>("CIN")
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .HasColumnType("text");

                            b1.Property<int?>("Gender")
                                .HasColumnType("integer");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .HasColumnType("text");

                            b1.HasKey("ChildId");

                            b1.ToTable("Children");

                            b1.WithOwner()
                                .HasForeignKey("ChildId");

                            b1.OwnsOne("PersonaManager.Domain.ValuesObject.Resource", "Avatar", b2 =>
                                {
                                    b2.Property<Guid>("IdentityChildId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ContentType")
                                        .HasColumnType("text");

                                    b2.Property<string>("Extensions")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Size")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Url")
                                        .HasColumnType("text");

                                    b2.HasKey("IdentityChildId");

                                    b2.ToTable("Children");

                                    b2.WithOwner()
                                        .HasForeignKey("IdentityChildId");
                                });

                            b1.Navigation("Avatar");
                        });

                    b.Navigation("Employee");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Contract", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonaManager.Domain.Entities.Employee", null)
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Department", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Department", null)
                        .WithMany("DepartmentsFils")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonaManager.Domain.Entities.Department", "ParentDepartment")
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId1");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Education", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Child", null)
                        .WithMany("Educations")
                        .HasForeignKey("ChildId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonaManager.Domain.Entities.Child", "Child")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonaManager.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PersonaManager.Domain.Entities.Employee", null)
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Child");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonaManager.Domain.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("PersonaManager.Domain.ValuesObject.Identity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("BirthPlace")
                                .HasColumnType("text");

                            b1.Property<string>("CIN")
                                .HasColumnType("text");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("Gender")
                                .HasColumnType("integer");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nationality")
                                .HasColumnType("text");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("PersonaManager.Domain.ValuesObject.Resource", "Avatar", b2 =>
                                {
                                    b2.Property<Guid>("IdentityEmployeeId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("ContentType")
                                        .HasColumnType("text");

                                    b2.Property<string>("Extensions")
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text");

                                    b2.Property<int?>("Size")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Url")
                                        .HasColumnType("text");

                                    b2.HasKey("IdentityEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("IdentityEmployeeId");
                                });

                            b1.Navigation("Avatar");
                        });

                    b.OwnsOne("PersonaManager.Domain.ValuesObject.Adress", "Adress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Area")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("District")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("PersonaManager.Domain.ValuesObject.CivilStatus", "CivilStatus", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaritalStatus")
                                .HasColumnType("integer");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("PersonaManager.Domain.ValuesObject.Identity", "Spouse", b2 =>
                                {
                                    b2.Property<Guid>("CivilStatusEmployeeId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("BirthDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("BirthPlace")
                                        .HasColumnType("text");

                                    b2.Property<string>("CIN")
                                        .HasColumnType("text");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("Gender")
                                        .HasColumnType("integer");

                                    b2.Property<string>("LastName")
                                        .HasColumnType("text");

                                    b2.Property<string>("Nationality")
                                        .HasColumnType("text");

                                    b2.HasKey("CivilStatusEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("CivilStatusEmployeeId");

                                    b2.OwnsOne("PersonaManager.Domain.ValuesObject.Resource", "Avatar", b3 =>
                                        {
                                            b3.Property<Guid>("IdentityCivilStatusEmployeeId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("ContentType")
                                                .HasColumnType("text");

                                            b3.Property<string>("Extensions")
                                                .HasColumnType("text");

                                            b3.Property<string>("Name")
                                                .HasColumnType("text");

                                            b3.Property<int?>("Size")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Url")
                                                .HasColumnType("text");

                                            b3.HasKey("IdentityCivilStatusEmployeeId");

                                            b3.ToTable("Employees");

                                            b3.WithOwner()
                                                .HasForeignKey("IdentityCivilStatusEmployeeId");
                                        });

                                    b2.Navigation("Avatar");
                                });

                            b1.Navigation("Spouse");
                        });

                    b.OwnsOne("PersonaManager.Domain.ValuesObject.Contact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string[]>("Email")
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("PhoneNumber")
                                .HasColumnType("text[]");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Adress");

                    b.Navigation("CivilStatus");

                    b.Navigation("Contact");

                    b.Navigation("Identity");

                    b.Navigation("Job");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Job", b =>
                {
                    b.HasOne("PersonaManager.Domain.Entities.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Child", b =>
                {
                    b.Navigation("Educations");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentsFils");
                });

            modelBuilder.Entity("PersonaManager.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Banks");

                    b.Navigation("Children");

                    b.Navigation("Contracts");

                    b.Navigation("Educations");
                });
#pragma warning restore 612, 618
        }
    }
}
